id: P009537
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:37:00.914581
source_metadata:
  id: bdr:W18640
  title: ཆོས་ཀྱི་བཟང་པོའི་རྣམ་ཐར
  author: ''
  volumes:
    c2eb31e797204eb1a42596468410074d:
      image_group_id: I1PD27424
      title: ''
      volume_number: 1
      total_pages: 10
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
